sudo : required
services:
  - docker

before_install:
  - docker build  -t onurcaydere/docker-try -f Dockerfile.dev .
script:
  - docker run -e CI=true onurcaydere/docker-try npm run test

#buraya kadar olan travisden build kontrolünü sağlıyor.

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app : "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-860003904213"
  bucket_path: "docker"
  on:
    branch: master
  access_key_ıd: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY


